title: Nepal Neurotechnology Research Center
email: govin2000@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: ismrm-anz
    display_name: ismrm-anz
    avatar: 'assets/images/sal.png'
    email: govin2000@gmail.com
    web: https://www.neurotechnepal.org  
    twitter: https://twitter.com/neurotech_nepal
    description: "Neurotechnology Research Center Nepal"
    
# Social
social:
  twitter: https://twitter.com/neurotech_nepal

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
